### PR TITLE
Don't discard built artifacts before running tests in CI

### PR DESCRIPTION
**Pull request by facundominguez**

### CODE REVIEW

**Comment by facundominguez** [comment]
Is calling `stack clean` before tests intentional?

It seems to be causing a rebuild of liquid-fixpoint in CI without an apparent reason.

**Comment by ranjitjhala** [comment]
oops no :-(

**Comment by facundominguez** [comment]
Well, that cut some 10 minutes of CI then :)

**Comment by facundominguez** [comment]
Is this good to merge?

**Comment by ranjitjhala** [comment]
thanks!!

**Pull request merged**
