### PR TITLE
Consider constructor applications as candidates for PLE

### LINKED ISSUE #489: Unfold measures when using PLE
It will take some debugging to figure out why this workaround was needed in liquidhaskell:
https://github.com/ucsd-progsys/liquidhaskell/pull/1874

I'm guessing that liquid-fixpoint should unfold measures with PLE, but please comment if we should consider other alternatives.

### PR DESCRIPTION
**Pull request by facundominguez**
Fixes #489

### CODE REVIEW

**Comment by facundominguez** [comment]
I checked that this runs MergeSort.hs in 35 seconds and it also passes the test introduced in ucsd-progsys/liquidhaskell#1874 without the code changes that are done there.

I'll be sharing benchmark comparisons later in the day.

**Comment by ranjitjhala** [comment]
OMG thank you 🙏

**Comment by facundominguez** [comment]
Well, nothing explodes. I think the first commit here accounts for most of the speed ups.

The chart below compares `origin/develop` in LH with https://github.com/ucsd-progsys/liquidhaskell/pull/1897.

perf

**Comment by ranjitjhala** [comment]
This looks great! (Facundo Iit just occurred to me I could have given you
merge access a long time ago!)

please go ahead and merge! Thanks!!

**Comment by facundominguez** [comment]
:+1: Alright, merging ....

**Pull request merged**
