### PR TITLE
Use cabal generation to check cabal file.

### PR DESCRIPTION
**Pull request by philderbeast**
I used [hpack-dhall](https://hackage.haskell.org/package/hpack-dhall) to generate `liquid-fixpoint.cabal` and then compared the existing file with the generated one. To enable me to more easily do the comparision I reordered some of the fields but tried to keep this to a minimum (sorry if the reformatting is annoying).

The changes are:

* homepage goes straight to the #readme
* added a bug-reports field
* found modules that were not `exposed-modules` or `other-modules` in the library
    ```
    Language.Fixpoint.Congruence.Closure
    Language.Fixpoint.Congruence.Types
    Language.Fixpoint.Types.Binary
    ```
* modules and dependencies are alphabetically sorted

I didn't change the copyright year but see that it is `2010-17`.

### CODE REVIEW

**Comment by philderbeast** [comment]
Do we need the `Binary.hs` module still? It seems very empty.

```
-- | We need Binary instances as they are used to serialize specs in LH...
--
module Language.Fixpoint.Types.Binary where

import qualified Data.Binary as B

import Language.Fixpoint.Types as F
```

**Comment by nikivazou** [comment]
Not entirely sure if the files you are deleting are dead code, so better if @ranjitjhala confirms.

**Comment by philderbeast** [comment]
@ranjitjhala are you OK if we delete those 3 modules?

**Comment by ranjitjhala** [comment]
Does LH build without those?

**Comment by facundominguez** [comment]
I don't see them imported anywhere, so they look safe to delete.

**Comment by ranjitjhala** [comment]
👍🏽

**Comment by facundominguez** [comment]
Merging this in #601.

**Pull request closed without merging**
