### PR TITLE
Nonlinear

### PR DESCRIPTION
**Pull request by nikivazou**
Make interpreted mul and div the default behavior

### CODE REVIEW

**Comment by gridaphobe** [comment]
How does this affect SMT solvers other than Z3? IIRC we claim to support CVC4 and MathSat as well.

**Comment by nikivazou** [comment]
Good point! We do not have these solvers in the test suite right? I am adding a `linear` flag so we can switch again in case of a problem

**Comment by gridaphobe** [comment]
I think we only test with Z3 at the moment. My point was more that we should try to ensure all solver backends work well out-of-the-box, e.g. if MathSat doesn't support non-linear arithmetic, then `--smtsolver mathsat` should imply `--linear`.

**Comment by gridaphobe** [comment]
(And this should be documented in the README and CHANGELOG!)

**Comment by nikivazou** [comment]
I bet most smt solvers support mul and div. Though, given that we are going into an (in theory) undecidable logic not sure how efficient they will be.

**Comment by gridaphobe** [comment]
But we shouldn't bet about the solvers we list in the README as supported, we should test! And even if they support interpreted mul and div, but produce sub-optimal results (e.g. timing out or returning "unknown") we should perhaps use the uninterpreted versions.

**Comment by nikivazou** [comment]
Ok, lets see what Z3 does first

**Comment by ranjitjhala** [comment]
@nikivazou -- can you add CSV files (performance) for before / after this
merge?

**Comment by nikivazou** [comment]
I have this https://github.com/ucsd-progsys/liquidhaskell/blob/bab3b940891809a6d7a5efe871faafebd2f784ad/tests/logs/defunctionalized.csv

and the one where the numbers are actually compared:

https://github.com/ucsd-progsys/liquidhaskell/blob/bab3b940891809a6d7a5efe871faafebd2f784ad/tests/logs/slowdown.csv

**Comment by gridaphobe** [comment]
@nikivazou Please update the CHANGELOG (and README if it mentioned `--real`)

**Comment by nikivazou** [comment]
I did in liquidHaskell

On Tue, Feb 9, 2016 at 1:56 PM, Eric Seidel <notifications@github.com>
wrote:

> @nikivazou <https://github.com/nikivazou> Please update the CHANGELOG
> (and README if it mentioned --real)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/pull/196#issuecomment-182094773>
> .
>



-- 
Niki Vazou

**Comment by gridaphobe** [comment]
Fixpoint is a separate package, and has its own changelog :)

**Comment by nikivazou** [comment]
Done!

**Pull request merged**
