### PR TITLE
Follow hlint suggestion to avoid lambda.

### PR DESCRIPTION
**Pull request by philderbeast**
Another one for #552.

### CODE REVIEW

**Comment by facundominguez** [comment]
Thanks @philderbeast. This is another one that we might want to continue to ignore, though. I find the lambda expressions easier to decipher than the point-free variants.

**Comment by philderbeast** [comment]
In this instance the hlint suggestions cascaded, first avoid lambda then use second then redundant bracket and then use section or something like that.

I put a stop to it after the avoid lambda first suggestion with an hlint annotation on `subExprs'` to ignore the next suggestion, to use second.

**Comment by facundominguez** [comment]
I'd rather not add HLint suggestions with the expectation that contributors will disable them where they make the code harder to read.

I'm closing this one without merging. But anyone feel free to challenge the choice.

**Comment by facundominguez** [comment]
I'd rather not add HLint suggestions with the expectation that contributors will disable them where they make the code harder to read.

I'm closing this one. But anyone feel free to challenge the choice.

**Pull request closed without merging**
