### PR TITLE
Parsing and printing AxiomEnv

### PR DESCRIPTION
**Pull request by atondwal**
This adds support for instantiation from plaintext fq files.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
​Nice! Is there an example .fq file that shows what the format is?

or is this still WIP? ​

also, what is this FUEL?

**Comment by atondwal** [comment]
Yep, it's

```
constant len: (func(1, [(Main.List  @(0)); int]))
constant Cons: (func(2, [@(0); (Main.List  @(0)); (Main.List @(0))]))
constant Nil: (Main.List @(0))

match len Nil = 0
match len Cons x xs = (1 + len xs)

constraint:
  env []
  lhs {v : int | true }
  rhs {v : int | len(Cons(1, Cons(2, Cons(3, Nil)))) = 3}
  id 1 tag []

expand [1 : True]
```

I'll push it into the tests dir after I add it to the test harness.

**Comment by atondwal** [comment]
Here's the corresponding LH PR, since I made a minor change to the AEnv API: 
https://github.com/ucsd-progsys/liquidhaskell/pull/1017

**Comment by nikivazou** [comment]
Why is this merged? It is not compatible with the LH develop

**Comment by atondwal** [comment]
Here's the LH PR: https://github.com/ucsd-progsys/liquidhaskell/pull/1017. I want to merge it, but I'm worried about circle...

**Pull request merged**
