### PR TITLE
liquid-fixpoint now builds with GHC 8

### PR DESCRIPTION
**Pull request by christetreault**

### CODE REVIEW

**Comment by nikivazou** [comment]
Great @christetreault! So, it builds with both GHC7 and 8 right?

**Comment by christetreault** [comment]
According to CircleCI it builds with GHC 7.10.2. I just added some `#if`'s in there, so I can't imagine it wouldn't

**Comment by gridaphobe** [comment]
Why are the instances not needed with GHC 8?

**Comment by ranjitjhala** [comment]
Is there any reason not to merge this? (i.e. will it break for us 7.10 weaklings?)

**Comment by christetreault** [comment]
Let's hold off on this one for the time being; these instances are probably used by liquid-haskell or something...

**Pull request closed without merging**
