### PR TITLE
Bottleneck pruning in AmericanFlag

### PR DESCRIPTION
**Pull request by facundominguez**
Here go some optimizations driven by profiling liquid-fixpoint when fed with AmericanFlag.hs.bfq

These optimizations clean up the flamegraph in #482. The remaining bottlenecks seem to be in smt interactions via pipe, serialization, and HashMap/Set lookups.

### CODE REVIEW

**Comment by facundominguez** [comment]
By now, I discovered the scripts to build performance charts from logs. [Here](https://github.com/ucsd-progsys/liquid-fixpoint/files/7149582/perf1.svg.zip) are the results. Above the noise level, I only see some improvements of a few seconds in some benchmarks.

**Comment by facundominguez** [comment]
... let me run one more performance check before merging this.

**Comment by facundominguez** [comment]
Checked. All is good. Feel free to merge.

**Comment by facundominguez** [comment]
Ping here :)

Do we need to do any more work to merge it?

I have some other optimizations to share, but I'd rather not grow this PR.

**Comment by ranjitjhala** [comment]
Thanks Facundo!

**Pull request merged**
