### PR TITLE
Steps towards reading in interpolated predicate

### PR DESCRIPTION
**Pull request by atondwal**
Not sure how to open a pull request against an not-yet-extant branch, but I guess cutsolver is the closest thing.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Thank!

I can merge this with cutsolver.

Any chance you can add a quick test of how to use the API, perhaps as a
comment somewhere? e.g. how to compute the interplant of:

  P: x = a /\ a = y
  Q: x > c /\ c > d

(i.e. something like the "top level" sequence of commands in GHCi that
would exercise
this API?)

Thanks!.



On Tue, Aug 11, 2015 at 6:14 AM, Anish Tondwalkar <notifications@github.com>
wrote:

> Not sure how to open a pull request against an not-yet-extant branch, but
> I guess cutsolver is the closest thing.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ucsd-progsys/liquid-fixpoint/pull/95
> Commit Summary
>
>    - Deps.hs: Added -X FlexibleContexts for ghc7.10
>    - steps towards reading in interpolated predicate
>    - Abstract away Lisp -> Pred
>    - bits of the Lisp -> Pred that don't depend on the types
>
> File Changes
>
>    - *M* src/Language/Fixpoint/Smt/Interface.hs
>    <https://github.com/ucsd-progsys/liquid-fixpoint/pull/95/files#diff-0>
>    (85)
>    - *M* src/Language/Fixpoint/Smt/Serialize.hs
>    <https://github.com/ucsd-progsys/liquid-fixpoint/pull/95/files#diff-1>
>    (1)
>    - *M* src/Language/Fixpoint/Smt/Types.hs
>    <https://github.com/ucsd-progsys/liquid-fixpoint/pull/95/files#diff-2>
>    (2)
>    - *M* src/Language/Fixpoint/Solver/Deps.hs
>    <https://github.com/ucsd-progsys/liquid-fixpoint/pull/95/files#diff-3>
>    (1)
>
> Patch Links:
>
>    - https://github.com/ucsd-progsys/liquid-fixpoint/pull/95.patch
>    - https://github.com/ucsd-progsys/liquid-fixpoint/pull/95.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/pull/95>.
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
Looks good, did you btw, run the tests?

**Comment by atondwal** [comment]
It yet doesn't work with the `N.hs` testcases we've been talking about (that needs a bunch more things, including more work on the smt2 parser --- should I make a TODO?), but with these commits it does run `.fq` files through the whole pipeline.`-f 3` indicates that the third constraint is the failing one we want to study with interpolation --- `liquid` will have to pass that in.

```
~/0/w/l/liquid-fixpoint ❯❯❯ fixpoint -n -i -f 3 tests/elim/test00a.fq                                                                                                                                                              ⏎ lisp ⬆ ✭ ◼
Liquid-Fixpoint Copyright 2009-13 Regents of the University of California.
All Rights Reserved.


**** DONE:  Read Constraints ***************************************************
 

**** DONE:  Uniqify ************************************************************
 

**** DONE:  Unroll *************************************************************
 
fixpoint: Not UNSAT. No interpolation needed. Why did you call upon me?
```

**Comment by gridaphobe** [comment]
@atondwal sorry, we just removed the OCaml binaries from the history of our repo to clean up a bunch of space, and this seems to have invalidated your PR. Can you port the patch over to the revised history and re-open? Something like 

```
git diff --patch > ../mybranch.patch
cd ..; git clone git://github.com/ucsd-progsys/liquid-fixpoint.git fixpoint-new; cd fixpoint-new
patch -p1 <../mybranch.patch
```

ought to work.

**Pull request closed without merging**
