### PR TITLE
Higher order quals (optionally) and currying on logical functions

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Do LH tests pass? Are all changed "optional"?  any performance hits?

**Comment by nikivazou** [comment]
LH tests pass

One change is optional: to use quals with function arguments (which leads to very bad performance)
The other edit (curry used defined logical functions) is not optional.

**Comment by gridaphobe** [comment]
What about performance implications?

**Comment by nikivazou** [comment]
Was just asking @christetreault how to easily compare performances

**Comment by ranjitjhala** [comment]
Are the performance comparisons done here? (where are the CSV files?)

**Pull request merged**
