### PR TITLE
Dump non-cuts kvars to fqout. Closes #484

### LINKED ISSUE #484: Disclose the value of non-cut KVars
When a subtyping constraint is rejected, sometimes it involves KVars. Like in
```
 lhs {VV : Language.Stitch.LH.Check.Exp | [((Language.Stitch.LH.Check.numFreeVarsExp VV) >= 0);
                                            $k_##2417[VV##2381:=VV][VV##3624:=VV][VV##F:=VV][lq_tmp$x##2378:=VV##3621][lq_tmp$x##2380:=lq_anf$##d4Pj][lq_tmp$x##2383:=VV][lq_tmp$x##3625:=VV]]}
  rhs {VV : Language.Stitch.LH.Check.Exp | [((Language.Stitch.LH.Check.exprType e0) = (Language.Stitch.LH.Check.exprType VV))]}
```

If the KVars are not eliminated by local refinement typing, they will end up in the .fqout files. However, if they are eliminated, they won't appear anywhere. And the user is left on her own to predict what the kvars are instantiated to.

Here's an example of what `$k_##2417` gets resolved to, and it looks like too much to ask from the user to guess.

```
exists [lq_karg$lq_anf$##7205759403792808828##d3XC##k_##2417 : (GHC.Maybe.Maybe Language.Stitch.LH.Check.Exp);
        lq_karg$e2##a3bm##k_##2417 : Language.Stitch.LH.Check.Exp;
        lq_karg$lq_anf$##7205759403792808829##d3XD##k_##2417 : (GHC.Maybe.Maybe Language.Stitch.LH.Check.Exp);
        lq_karg$lq_anf$##7205759403792808830##d3XE##k_##2417 : (GHC.Maybe.Maybe Language.Stitch.LH.Check.Exp);
        lq_karg$lq_anf$##7205759403792808832##d3XG##k_##2417 : Language.Stitch.LH.Type.Ty;
        lq_karg$lq_anf$##7205759403792808835##d3XJ##k_##2417 : Language.Stitch.LH.Check.Exp;
        lq_karg$e11##a3bq##k_##2417 : Language.Stitch.LH.Check.Exp;
        lq_karg$VV##2416##k_##2417 : Language.Stitch.LH.Check.Exp;
        lq_karg$lq_anf$##7205759403792808827##d3XB##k_##2417 : (GHC.Maybe.Maybe Language.Stitch.LH.Check.Exp);
        lq_karg$lq_anf$##7205759403792808833##d3XH##k_##2417 : Language.Stitch.LH.Type.Ty;
        lq_karg$e1##a3bl##k_##2417 : Language.Stitch.LH.Check.Exp;
        lq_karg$ty##a3bp##k_##2417 : Language.Stitch.LH.Type.Ty;
        lq_karg$lq_anf$##7205759403792808825##d3Xz##k_##2417 : Language.Stitch.LH.Check.Exp;
        lq_karg$lq_anf$##7205759403792808834##d3XI##k_##2417 : Language.Stitch.LH.Check.Exp;
        lq_karg$e0##a3bk##k_##2417 : Language.Stitch.LH.Check.Exp;
        lq_karg$lq_anf$##7205759403792808831##d3XF##k_##2417 : Language.Stitch.LH.Check.Exp]
       . && [(lq_karg$VV##2416##k_##2417 = VV##F##148);
             (lq_karg$e0##a3bk##k_##2417 = e0##a3bk);
             (lq_karg$e1##a3bl##k_##2417 = e1##a3bl);
             (lq_karg$e11##a3bq##k_##2417 = e11##a3bq);
             (lq_karg$e2##a3bm##k_##2417 = e2##a3bm);
             (lq_karg$lq_anf$##7205759403792808825##d3Xz##k_##2417 = lq_anf$##7205759403792808825##d3Xz);
             (lq_karg$lq_anf$##7205759403792808827##d3XB##k_##2417 = lq_anf$##7205759403792808827##d3XB);
             (lq_karg$lq_anf$##7205759403792808828##d3XC##k_##2417 = lq_anf$##7205759403792808828##d3XC);
             (lq_karg$lq_anf$##7205759403792808829##d3XD##k_##2417 = lq_anf$##7205759403792808829##d3XD);
             (lq_karg$lq_anf$##7205759403792808830##d3XE##k_##2417 = lq_anf$##7205759403792808830##d3XE);
             (lq_karg$lq_anf$##7205759403792808831##d3XF##k_##2417 = lq_anf$##7205759403792808831##d3XF);
             (lq_karg$lq_anf$##7205759403792808832##d3XG##k_##2417 = lq_anf$##7205759403792808832##d3XG);
             (lq_karg$lq_anf$##7205759403792808833##d3XH##k_##2417 = lq_anf$##7205759403792808833##d3XH);
             (lq_karg$lq_anf$##7205759403792808834##d3XI##k_##2417 = lq_anf$##7205759403792808834##d3XI);
             (lq_karg$lq_anf$##7205759403792808835##d3XJ##k_##2417 = lq_anf$##7205759403792808835##d3XJ);
             (lq_karg$ty##a3bp##k_##2417 = ty##a3bp);
             exists [GHC.Types.False : bool;
                     GHC.Types.True : bool;
                     VV##F##151 : Language.Stitch.LH.Check.Exp]
                    . && [GHC.Types.True;
                          (((apply  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                 bool])) (((apply  :  func(0 , [(Language.Stitch.LH.Data.List.List Language.Stitch.LH.Type.Ty);
                                                                                Language.Stitch.LH.Check.Exp;
                                                                                bool])) (Language.Stitch.LH.Check.checkBindings  :  func(0 , [(Language.Stitch.LH.Data.List.List Language.Stitch.LH.Ty
pe.Ty);
                                                                                                                                              Language.Stitch.LH.Check.Exp;
                                                                                                                                          bool])) 
(Language.Stitch.LH.Data.List.Nil  :  (Language.Stitch.LH.Data.List.List Language.Stitch.LH.Type.Ty)))  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                                                                                                                                                                                                                                           bool])) (VV##F##151  :  Language.Stitch.LH.Check.Exp))  :  bool);
                          (~ (GHC.Types.False));
                          (lq_karg$VV##2416##k_##2417 = VV##F##151);
                          (lq_karg$e0##a3bk##k_##2417 = e0##a3bk);
                          (lq_karg$e1##a3bl##k_##2417 = e1##a3bl);
                          (lq_karg$e11##a3bq##k_##2417 = e11##a3bq);
                          (lq_karg$e2##a3bm##k_##2417 = e2##a3bm);
                          (lq_karg$lq_anf$##7205759403792808825##d3Xz##k_##2417 = lq_anf$##7205759403792808825##d3Xz);
                          (lq_karg$lq_anf$##7205759403792808827##d3XB##k_##2417 = lq_anf$##7205759403792808827##d3XB);
                          (lq_karg$lq_anf$##7205759403792808828##d3XC##k_##2417 = lq_anf$##7205759403792808828##d3XC);
                          (lq_karg$lq_anf$##7205759403792808829##d3XD##k_##2417 = lq_anf$##7205759403792808829##d3XD);
                          (lq_karg$lq_anf$##7205759403792808830##d3XE##k_##2417 = lq_anf$##7205759403792808830##d3XE);
                          (lq_karg$lq_anf$##7205759403792808831##d3XF##k_##2417 = lq_anf$##7205759403792808831##d3XF);
                          (lq_karg$lq_anf$##7205759403792808832##d3XG##k_##2417 = lq_anf$##7205759403792808832##d3XG);
                          (lq_karg$lq_anf$##7205759403792808833##d3XH##k_##2417 = lq_anf$##7205759403792808833##d3XH);
                          (lq_karg$lq_anf$##7205759403792808834##d3XI##k_##2417 = lq_anf$##7205759403792808834##d3XI);
                          (lq_karg$lq_anf$##7205759403792808835##d3XJ##k_##2417 = lq_anf$##7205759403792808835##d3XJ);
                          (lq_karg$ty##a3bp##k_##2417 = ty##a3bp);
                          ((VV##F##151  :  Language.Stitch.LH.Check.Exp) = (lq_anf$##7205759403792808835##d3XJ  :  Language.Stitch.LH.Check.Exp));
                          ((((apply  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                  Language.Stitch.LH.Type.Ty])) (Language.Stitch.LH.Check.exprType  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                                                                                                 Language.Stitch.LH.Type.Ty])) (lq_anf$##7205759403792808834##d3XI  :  Language.Stitch.LH.Check.Exp))  :  Language.Stitch.LH.Type.Ty) = (((apply  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                                                                                                                                                                                                                                                               Language.Stitch.LH.Type.Ty])) (Language.Stitch.LH.Check.exprType  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                                                                                                                                                                                                                                                                                                                                              Language.Stitch.LH.Type.Ty])) (VV##F##151  :  Language.Stitch.LH.Check.Exp))  :  Language.Stitch.LH.Type.Ty));
                          ((true  :  bool) = (GHC.Types.True  :  bool));
                          ((false  :  bool) = (GHC.Types.False  :  bool));
                          ((((apply  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                  int])) (Language.Stitch.LH.Check.numFreeVarsExp  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                                                                                int])) (VV##F##151  :  Language.Stitch.LH.Check.Exp))  :  int) >= 0);
                          ((((apply  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                  int])) (Language.Stitch.LH.Check.numFreeVarsExp  :  func(0 , [Language.Stitch.LH.Check.Exp;
                                                                                                                int])) (VV##F##151  :  Language.Stitch.LH.Check.Exp))  :  int) <= (((apply  :  func(0 , [(Language.Stitch.LH.Data.List.List @(44));
                                                                                                                                                                                                         int])) (Language.Stitch.LH.Data.List.length  :  func(0 , [(Language.Stitch.LH.Data.List.List @(44));
                                                                                                                                                                                                                                                                   int])) (Language.Stitch.LH.Data.List.Nil  :  (Language.Stitch.LH.Data.List.List @(44))))  :  int))]])
```

The predicate to replace the kvar is constructed [here](https://github.com/ucsd-progsys/liquid-fixpoint/blob/bcfccde04d5fc7265c8796134b3a638a36e7a836/src/Language/Fixpoint/Solver/Solution.hs#L345). The lookup yields `Left cs` for non-cut KVars. It would be easy enough to add these predicates as part of the `Result` or `FixSolution` types and have them printed in `.fqout` files.

### PR DESCRIPTION
**Pull request by facundominguez**

### CODE REVIEW

**Comment by facundominguez** [comment]
With this change, non-cut variables are printed to fqout files. e.g.
```
Solution:
...
Non-cut kvars:

$k_##1471 := false

$k_##2183 := false

$k_##2209 := false

$k_##2286 := false

$k_##2321 := exists [lq_karg$e11##a4Tl##k_##2321 : Language.Stitch.LH.Check.Exp;
                     lq_karg$lq_anf$##7205759403792812837##d50h##k_##2321 : Language.Stitch.LH.Check.Exp;
                     lq_karg$lq_anf$##7205759403792812842##d50m##k_##2321 : (GHC.Maybe.Maybe Language.Stitch.LH.Check.Exp);
                     lq_karg$VV##2320##k_##2321 : Language.Stitch.LH.Check.Exp;
                     lq_karg$lq_anf$##7205759403792812839##d50j##k_##2321 : (GHC.Maybe.Maybe Language.Stitch.LH.Check.Exp);
                     lq_karg$e1##a4Tg##k_##2321 : Language.Stitch.LH.Check.Exp;
                     lq_karg$lq_anf$##7205759403792812844##d50o##k_##2321 : Language.Stitch.LH.Check.Exp;
                     lq_karg$e0##a4Tf##k_##2321 : Language.Stitch.LH.Check.Exp;
                     lq_karg$lq_anf$##7205759403792812840##d50k##k_##2321 : (GHC.Maybe.Maybe Language.Stitch.LH.Check.Exp);
                     lq_karg$ty##a4Tk##k_##2321 : Language.Stitch.LH.Type.Ty;
                     lq_karg$lq_anf$##7205759403792812843##d50n##k_##2321 : Language.Stitch.LH.Check.Exp;
                     lq_karg$lq_anf$##7205759403792812841##d50l##k_##2321 : (GHC.Maybe.Maybe Language.Stitch.LH.Check.Exp);
                     lq_karg$e2##a4Th##k_##2321 : Language.Stitch.LH.Check.Exp;
                     VV##F##146 : Language.Stitch.LH.Check.Exp;
                     GHC.Types.False : bool;
                     GHC.Types.True : bool]
               . GHC.Types.True
                 && Language.Stitch.LH.Check.checkBindings Language.Stitch.LH.Data.List.Nil VV##F##146
                 && not GHC.Types.False
                 && lq_karg$VV##2320##k_##2321 == VV##F##146
                 && lq_karg$e0##a4Tf##k_##2321 == e0##a4Tf
                 && lq_karg$e1##a4Tg##k_##2321 == e1##a4Tg
                 && lq_karg$e11##a4Tl##k_##2321 == e11##a4Tl
                 && lq_karg$e2##a4Th##k_##2321 == e2##a4Th
                 && lq_karg$lq_anf$##7205759403792812837##d50h##k_##2321 == lq_anf$##7205759403792812837##d50h
                 && lq_karg$lq_anf$##7205759403792812839##d50j##k_##2321 == lq_anf$##7205759403792812839##d50j
                 && lq_karg$lq_anf$##7205759403792812840##d50k##k_##2321 == lq_anf$##7205759403792812840##d50k
                 && lq_karg$lq_anf$##7205759403792812841##d50l##k_##2321 == lq_anf$##7205759403792812841##d50l
                 && lq_karg$lq_anf$##7205759403792812842##d50m##k_##2321 == lq_anf$##7205759403792812842##d50m
                 && lq_karg$lq_anf$##7205759403792812843##d50n##k_##2321 == lq_anf$##7205759403792812843##d50n
                 && lq_karg$lq_anf$##7205759403792812844##d50o##k_##2321 == lq_anf$##7205759403792812844##d50o
                 && lq_karg$ty##a4Tk##k_##2321 == ty##a4Tk
                 && VV##F##146 == lq_anf$##7205759403792812844##d50o
                 && Language.Stitch.LH.Check.exprType e11##a4Tl == Language.Stitch.LH.Check.exprType VV##F##146
                 && true == GHC.Types.True
                 && false == GHC.Types.False
                 && Language.Stitch.LH.Check.numFreeVarsExp VV##F##146 >= 0
                 && Language.Stitch.LH.Check.numFreeVarsExp VV##F##146 <= Language.Stitch.LH.Data.List.length Language.Stitch.LH.Data.List.Nil
```

See the comments of `bareCubePred` for small differences with the predicates used in the verification pipeline.

**Review by ranjitjhala — APPROVED** [review]

**Comment by ranjitjhala** [comment]
Wow this is awesome thanks! [I wonder if there will be some big slowdown though -- do you know if the saving is guarded by some flag eg `--save` ?]

**Comment by facundominguez** [comment]
It is not guarded. Do you want to print `.fqout` files only on `--save`?

**Comment by ranjitjhala** [comment]
If it’s any easy addition to this PR I think that would be good.

**Comment by facundominguez** [comment]
CI is green.

**Pull request merged**
