### PR TITLE
Dev.jp

### PR DESCRIPTION
**Pull request by nikivazou**
Edits to address memory leaks in fixpoint

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Nice!

Can we first merge this against a separate
branch of LF (not `develop`) so we can build
against (plain) LH and generate the `summary.csv`
files to ensure this doesn't cause any
strange performance regressions?

Thanks!

**Comment by ranjitjhala** [comment]
@nikivazou  see this, 

https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/

can you change this PR to a separate, e.g. `strictness` or `jp` branch so we can 
check the performance of @jprider63 's code systematically before merging into 
`develop`.

Thanks!

**Comment by ranjitjhala** [comment]
Cool, looks like I can do it myself :) ... will fire up the LH runs.

**Comment by jprider63** [comment]
Is it possible to run CI tests? I'd like to verify I haven't broken things :)

**Comment by ranjitjhala** [comment]
Hmm. wonder why the `fixpoint` CI didn't run automatically on the above?

Just created and pushed a `jp-strict` for LH to trigger CI...

**Pull request merged**
