### PR TITLE
Bindenv Fix and SubC simplification

### LINKED ISSUE #125: Nonconsecutive BindIds
See:

https://github.com/ucsd-progsys/liquid-fixpoint/blob/5909e1a2ef03f4a228a67292279179e20076a286/tests/todo/nonconsec-bindids.fq

It passes if you rename bind 3 (and its use site) to say 2 or 5.

Currently, insertBindEnv assumes BindIds have been assigned consecutively, and so its users (in our case, Validate's renameVV) may trample some binders when they're not consecutive. Do we modify insertBindEnv, or do we enforce the consecutive invariant (which would at least involve modifying the other Validate passes that drop binders)?

### PR DESCRIPTION
**Pull request by bmcfluff**
Fixes #125 and #126. The Haskell solver now uses a simpler internal representation of a subtyping constraint, with some rather hacky wrapper classes to keep the external interface the same.

### CODE REVIEW

**Comment by bmcfluff** [comment]
LH-derived Fixpoint test status after this PR: "11 out of 365 tests failed (1931.64s)"

**Comment by ranjitjhala** [comment]
very nice!! Out of curiosity, what are those 11?


On Thursday, September 10, 2015, bmcfluff <notifications@github.com> wrote:

> LH-derived Fixpoint test status after this PR: "11 out of 365 tests failed
> (1931.64s)"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/pull/132#issuecomment-139449120>
> .
>


-- 
Ranjit.

**Comment by ranjitjhala** [comment]
Btw, just to be sure DELETE `tests/pos/.liquid` and `tests/neg/.liquid` and
any other such directories just to ensure this is not some happy
coincidence of caching the results from the ocaml solver...




>
>

> On Thursday, September 10, 2015, bmcfluff <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> LH-derived Fixpoint test status after this PR: "11 out of 365 tests
>> failed (1931.64s)"
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ucsd-progsys/liquid-fixpoint/pull/132#issuecomment-139449120>
>> .
>>
>
>
> --
> Ranjit.
>
>

-- 
Ranjit.

**Comment by bmcfluff** [comment]
Rerunning after deleting .liquid again just in case.

The 11 pos tests that fail (half due to #133):
pair00.hs.fq
pair0.hs.fq
OrdList.hs.22.fq
maps1.hs.fq
maps.hs.fq
LocalTermExpr.hs.fq
LocalHole.hs.fq
Holes.hs.fq
eqelems.hs.fq
alphaconvert-List.hs.fq
absref-crash0.hs.fq

And the 9 neg tests that fail:
wrap0.hs.fq
Strata.hs.fq
pair0.hs.fq
MeasureDups.hs.fq
mapreduce.hs.3.fq
mapreduce.hs.2.fq
csv.hs.3.fq
csv.hs.1.fq
AutoSize.hs.fq

**Comment by bmcfluff** [comment]
Yep, it's happy but it's not a coincidence.

**Comment by bmcfluff** [comment]
Can we merge this?

**Comment by ranjitjhala** [comment]
merging since it has nothing to do with the weird LH regression 

https://github.com/ucsd-progsys/liquidhaskell/issues/453

**Pull request merged**
