### PR TITLE
Bumping version number to 0.5

### PR DESCRIPTION
**Pull request by christetreault**
OK, break it all you want, the version has been bumped. I'll make LH in the repo depend on `liquid-fixpoint == 0.5.*` so it won't try to install from hackage.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Super -- just to be sure, you will (have)  also bump(ed) the LH version
right?  Thanks!

In general, can you draft a small para explaining "the protocol" and add it
to the README
for liquid-fixpoint?

Thanks!

Ranjit.


On Tuesday, September 22, 2015, Chris Tetreault <notifications@github.com>
wrote:

> OK, break it all you want, the version has been bumped. I'll make LH in
> the repo depend on liquid-fixpoint == 0.5.* So it won't try to install
> from hackage.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ucsd-progsys/liquid-fixpoint/pull/143
> Commit Summary
>
>    - Bumping version number to 0.5
>
> File Changes
>
>    - *M* liquid-fixpoint.cabal
>    <https://github.com/ucsd-progsys/liquid-fixpoint/pull/143/files#diff-0>
>    (2)
>
> Patch Links:
>
>    - https://github.com/ucsd-progsys/liquid-fixpoint/pull/143.patch
>    - https://github.com/ucsd-progsys/liquid-fixpoint/pull/143.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquid-fixpoint/pull/143>.
>


-- 
Ranjit.

**Comment by gridaphobe** [comment]
There's no need to bump the LH major version if we haven't (yet) broken
anything. A minor bump would be in order though.

There's a bit more than a paragraph at http://semver.org (Haskell's PVP
is slightly different, but the basic idea is the same IIRC).

**Comment by ranjitjhala** [comment]
Ah, I'm not looking for a detailed description; just a CHECKLIST of
Instructions of the form:

+ In repo X change file Y to Z
...

**Comment by christetreault** [comment]
I find the PVP versioning to be strange, personally. If I understand correctly, for version `A.B.C.D`, `A.B` is for breaking changes, `C` is for non-breaking additions, and `D` is for "whatever you feel like doing, GOSH!" That said, it's the official policy of "our community" so I imagine we should follow that instead of the usual semantic versioning.

I'm thinking the versioning instructions can say something to the effect of "When a release is made to hackage, bump digit `C` by 1. If a breaking change is made to the repo, set `C` to 0, and bump `B` by 1." `A` will of course be sacred and only modifiable by a grownup.

**Comment by christetreault** [comment]
@ranjitjhala I'll bump the version of liquid haskell as part of my changes for https://github.com/ucsd-progsys/liquidhaskell/issues/461 which will hopefully be done today. I had made progress yesterday, but managed to break my haskell installation.

**Comment by gridaphobe** [comment]
Ooh [bumper](https://github.com/silkapp/bumper/blob/master/README.md) looks super useful.

Here's roughly how it should be used, assuming you're in the "top-level" liquid directory, i.e.

```
liquid
 |- liquid-fixpoint
 |- liquidhaskell
 |- refscript
 \- etc.
```

- If you change any exported type signature: `bumper --major liquid-fixpoint`
- If you add a new exported function: `bumper --minor liquid-fixpoint`
- Upon releasing to hackage: `bumper -3 liquid-fixpoint`

bumper will supposedly handle the transitive version bumps to liquidhaskell and other packages.

**Comment by christetreault** [comment]
Is refscript something I need to be concerned about? How many projects do we control that have a dependency on fixpoint?

**Comment by gridaphobe** [comment]
refscript isn't on hackage, so not really

http://packdeps.haskellers.com/reverse/liquid-fixpoint shows that
liquidhaskell and target are the only released projects. i develop
target against the hackage release of fixpoint/LH (which is much more
sane IMO) so you don't need to worry about it either.

**Comment by christetreault** [comment]
This bumper thing seems reasonable. I'll give it a shot and see how it goes. I can probably write a few bash scripts to do the right thing if it works out and our documentation for versioning will be "run the script"

**Comment by christetreault** [comment]
We don't re-export anything from fixpoint in liquid do we?

**Comment by ranjitjhala** [comment]
Yes we should worry about RefScript -- as in this policy should be applied across the board regardless of whether or not the package is (yet) on hackage.

**Comment by christetreault** [comment]
OK, I don't seem to have access to that repo, so I'm going to need to get added if I'm going to include it.

**Comment by christetreault** [comment]
Bumper seems to work. I'll go about updating the docs to use it. I'm not sure it's worth writing a script to do `./bumper --major liquid-fixpoint` so I'll probably skip that part.

**Comment by bmcfluff** [comment]
@christetreault - by re-exporting, are you referring e.g. to "isDummy" (https://github.com/ucsd-progsys/liquid-fixpoint/blob/master/src/Language/Fixpoint/Types.hs#L165) (https://github.com/ucsd-progsys/liquidhaskell/blob/master/src/Language/Haskell/Liquid/Types.hs#L39)? Not sure why we're doing that (and now might be the time to fix it...)

**Comment by christetreault** [comment]
Yeah, that is what I'm talking about. If the signature of that is changed by fixpoint, then liquid has to get a major version bump.

That said, I think the way to go is to have separate versioning instructions for liquid, similar to what I'm doing right now in fixpoint. Those instructions can address that, since we don't maintain anything that fixpoint depends on, we don't have to worry about these issues.

**Comment by christetreault** [comment]
OK, how does this look? https://github.com/ucsd-progsys/liquid-fixpoint/tree/bump-version#configuration-management

**Comment by bmcfluff** [comment]
The bumper utility doesn't seem to put trailing 0s on version numbers.

**Comment by christetreault** [comment]
Yeah, but that's purely aesthetic. I guess I could update the instructions to match that, but I think people will figure it out.

**Comment by christetreault** [comment]
Hmm... This might actually be a real problem...

https://github.com/haskell/cabal/issues/1368

**Comment by christetreault** [comment]
```
Prelude Data.Version> Version [0,5] [] >= Version [0,5,0] []
False
Prelude Data.Version> Version [0,5] [] <= Version [0,5,0] []
True
Prelude Data.Version> Version [0,5] [] == Version [0,5,0] []
False

```

I'll update the docs to specify stripping the trailing zeros.

**Comment by christetreault** [comment]
OK, thanks @bmcfluff for thinking of that. Now the instructions specify stripping trailing zeros, so we shouldn't run into this issue.

**Pull request merged**
