### PR TITLE
Test matrix with updated tested-with range.

### PR DESCRIPTION
**Pull request by philderbeast**
Add github actions for testing with cabal and stack, for #564 and before getting started on #538.

I didn't remove the circleci test. I did however add `stack.yaml`. That won't bother the github stack action because it picks up its own `stack/stack-8.10.7.yaml` but it might bother the circleci test.

### CODE REVIEW

**Comment by philderbeast** [comment]
The top of the readme rendered:

Screen Shot 2022-04-28 at 11 59 35 AM

**Comment by philderbeast** [comment]
The "single-level anf vars" test #557 is failing often enough now to upset merge checks.

**Comment by facundominguez** [comment]
I think we can drop testing with ghc-8.8.4 and ghc-9.0.2. @nikivazou, @ranjitjhala, any thoughts?

**Comment by facundominguez** [comment]
I'm merging this in #591. I'm removing 8.8.4 and 9.0.2 jobs, but we can add those later if they are needed.

**Comment by ranjitjhala** [comment]
884 Sounds good but why 9?

**Comment by facundominguez** [comment]
There's a job for 9.2.2 to check that LF stays on top of GHC changes. Do you still want to check the intermediate 9.0.2?

**Comment by ranjitjhala** [comment]
I think 9.2.2 is quite sufficient! Thank you!

**Pull request closed without merging**
