### PR TITLE
Ghc 8

### PR DESCRIPTION
**Pull request by nikivazou**
This is what Liquid Haskell develop depends on, so better if this is the fixpoint develop.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
@nikivazou -- I don't have a strong opinion either way, but in general we can keep the older dependency, and when ppl are building with LH, then cabal/stack should do the right thing,
right?

**Comment by gridaphobe** [comment]
Yes, there's no reason to base fixpoint's requirements on LH's. Cabal/Stack will sort out the dependencies correctly.

**Comment by nikivazou** [comment]
Ok! My main problem is that I am used to merge my local under-development branch to the current develop. 
But now that I did that, my gradual branch is not compatible with LH.

**Comment by gridaphobe** [comment]
I don't follow, what precisely happens?

**Comment by nikivazou** [comment]
Just that the current Fixpoint develop does not build with the current Liquid Haskell develop. 
Which I do not like, but not such a huge issue.

**Comment by gridaphobe** [comment]
But why does it not build? I don't see how the change to the lower bound for `base` could affect the LF/LH compatibility.

**Pull request merged**
